name: Protect Main Branch

on:
  workflow_dispatch:

jobs:
  protect-main:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Branch Protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const branch = 'main';
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts: ["Verify code compiling and tests running through"]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: false,
                require_code_owner_reviews: false,
                required_approving_review_count: 1
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              required_linear_history: true,
              block_creations: false,
              required_conversation_resolution: true
            });
