name: Java CI to create and upload jar to latest release
on:
  release:
    types: [created]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build jar
        run: ./gradlew clean build jar

      - run: mv build/libs/*.jar build/libs/$GITHUB_REF_NAME.jar

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/libs/$GITHUB_REF_NAME.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- uses: AButler/upload-release-assets@v3.0
      #  with:
      #    files: "build/libs/*.jar"
      #    repo-token: ${{ secrets.GITHUB_TOKEN }}