name: Apply Branch Protection Rules

on:
  push:
    branches:
      - main
  #workflow_dispatch: # or push, or repository_dispatch if automating after creation

permissions:
  contents: write
  actions: write
  administration: write

jobs:
  protect-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Branch Protection Rules
        uses: actions/github-script@v7
        with:
          script: |
            const branch = 'main';
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts: ['Verify code compiling and tests running through (CI)'] // replace with your required status checks
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1
              },
              restrictions: null, // no user/team restrictions
              allow_force_pushes: false,
              allow_deletions: false,
              required_linear_history: true,
              block_creations: false,
              required_conversation_resolution: true
            });